<h3>LiteracyDecision</h3>
<h4>Estimation Approach</h4>
<p>Based on the survey data alone, the 2003 National Assessment of Adult Literacy (NAAL) and 1992 National Adult Literacy Survey (NALS) surveys were not designed to provide policymakers and educators with estimates of the percentages of adults at the lowest literacy level for all U.S. states and counties. To address the need for such estimates, a statistical model was developed to produce indirect (i.e., model dependent) estimates of the percentages of adults lacking <em>Basic Prose Literacy Skills (<em>BPLS</em>)</em> (see note 1, below) based on the 2003 NAAL data. The same modeling approach was then applied to the 1992 NALS data. A Hierarchical Bayes model was adopted using a Markov Chain Monte Carlo (MCMC) method (Gelman et al. 2004) and implemented using the WinBUGS software (Lunn et al. 2000). The key components of the modeling approach were to develop (1) a sampling model for the sampling variability present in the county level, direct survey estimates of the county percentages of adults lacking <em>BPLS</em> estimates (for counties with some respondents) and (2) a logit model (linear logistic regression model) to predict the survey estimates from a set of auxiliary variables that were available and measured consistently for all counties.</p>
<h4>From Direct County Estimates To Indirect County Estimates</h4>
<p>A large pool of items was used in the literacy assessment to enable the surveys to cover a broad range of literacy tasks. However, to keep the testing time at a reasonable level, only a subset of the items in the item pool was administered to each participant. Since respondents took different sets of items that could be different in level of difficulty, it would be inappropriate to base the literacy estimates simply on the number of correct answers obtained. Instead, a marginal maximum likelihood method was applied to represent each individual's estimated proficiency as a probability distribution over all possible scores. The probability distributions for sampled individuals were then used in the estimation process to compute direct estimates of the percentage of adults lacking <em>BPLS</em> for individual counties included in the NAAL or NALS samples.</p>
<p>Variance estimates were then produced for the direct county estimates using a Taylor series approximation that took account of the survey weights and the clustered sample design within counties (see, for example, Wolter 1985). Given the relatively small sample sizes in most counties, the direct estimates were generally imprecise. Since the variance estimates were also subject to considerable sampling variability, they were smoothed using a generalized variance function approach. The direct estimates and smoothed variance estimates for the sampled counties were then used in the subsequent logit model analysis to compute model-dependent, indirect estimates for all counties in the United States.</p>
<h4>Predictor Variables</h4>
<p>A key aspect of the small area estimation modeling for the 2003 NAAL was finding auxiliary variables that are measured consistently across all U.S. counties and that are effective predictors of the county percentages of adults lacking <em>BPLS</em>. The process of model development involved the compilation of a large number of auxiliary variables that were known or hypothesized to be correlated with literacy. The final set of predictors was selected based on its ability to best account for the between-county variation in the direct estimates of the percentage lacking BPLS for sampled counties.</p>
<p>The best set of predictors for the 2003 NAAL model comprised the following six variables:</p>
<ul class="basic">
	<li>Percentage of the county population who were foreign-born and who had stayed in the United States for 20 years or less years;</li>
	<li>Percentage of county population age 25 and older with only a high school education or less;</li>
	<li>Percentage of the county population who were Black or Hispanic;</li>
	<li>Percentage of the county population in households with incomes below 150 percent of poverty level;</li>
	<li>Indicator variable identifying the New England and North Central census divisions; and</li>
	<li>Indicator variable identifying the SAAL states.</li>
</ul>
<p>All predictor variables were obtained from the Census of Population Summary File 3, with the exception of the SALS state indicator.</p>
<h4>Small Area Model For Census Block Group Estimates</h4>
<p>A single area-level statistical model that acknowledges the sampling variability present in the dependent variable was used to predict the county percentages of adults lacking <em>BPLS</em>. The logit of the direct county-level estimated percentages of adults lacking <em>BPLS</em> was used as the dependent variable in the model and the county-level variables described above were used as the predictor variables. The logit model also included random state and county effects.</p>
<p>Using Census Block Group level predictor variables for Clark County, this logit model was applied.  The resulting estimates were compared to the county level estimates for Clark County and fall within the 95% confidence interval.</p>
<h4>Note 1: Basic Prose Literacy Skills (BPLS)</h4>
<p>Trained interviewers, some of whom were bilingual in English and Spanish, visited households to select and interview adults. Each study participant was asked questions about his or her demographic characteristics, educational background, reading practices, and other areas related to literacy. These questions were available in English and Spanish. Participants were then presented with either the NAAL or NALS literacy assessment, which contained a series of diverse English literacy tasks for them to answer. With the exception of certain core assessment tasks, the instructions for these tasks were presented in English only. The literacy of adults who lack <em>BPLS</em> ranges from being unable to read and understand any written information in English to being able to locate easily identifiable information in short, commonplace prose text, but nothing more advanced. The estimates include adults who were not able to communicate in English or Spanish and could not be tested, classifying them as lacking <em>BPLS</em>. These estimates therefore differ from the estimates of the percentages Below Basic published in NAAL and NALS reports: adults who could not communicate in English or Spanish are excluded entirely in the calculations of the latter estimates.</p>
<h4>References</h4>
<p>Gelman, A., Carlin, J., Stern, H., and Rubin, D. (2004). <em>Bayesian Data Analysis. 2nd edition. Texts in statistical science.</em> Chapman and Hall/CRC.</p>
<p>Lunn, D.J., Thomas, A., Best, N., and Spiegelhalter, D. (2000). <em>WinBUGS—A Bayesian modeling framework: Concepts, structure, and extensibility, Statistics and Computing, </em>10(4): 325-337.</p>
<p>Wolter, K. (1985). <em>Introduction to Variance Estimation. </em>New York: Springer-Verlag.</p>


<div style="clear: both;">&nbsp;</div>
